version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:13.1-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.dev
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env.dev
    ports:
      - 80:80
